apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset
  labels:
    app: replicaset
spec:
  selector:
    matchLabels:
      app: replicaset-app
  replicas: 4
  template:
      metadata:
        name: nginx
        labels:
          app: replicaset-app
      spec:
        containers:
          - name: nginx
            image: nginx