apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    app: demo-app
    name: result-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
  selector:
    app: demo-app
    name: result-pod