apiVersion: v1
kind: Pod
metadata:
  name: voting-pod
  labels:
    app: demo-app
    name: voting-pod
spec:
  containers:
    - name: vote
      image: kodekloud/examplevotingapp_vote:v1
      ports:
        - containerPort: 80