apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    app: demo-app
    name: voting-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
  selector:
    app: demo-app
    name: voting-pod